### ISSUE TITLE
Diep Has Protection Against Modified Game Clients

### ISSUE THREAD

**Issue by Windfall-Github** [terjanq/xDiep.io#11]
Diep Has Protection Against Modified Game Clients, and whenever you start diep, you login and start playing and then message pops up (shown below) it says they will start banning soon and screen goes black.
![diep io-dieplusdoes not work](https://cloud.githubusercontent.com/assets/25651379/22765364/ae9c6720-ee24-11e6-9642-4e0cb87148d0.jpg)

Thanks, and keep up the great work-
oneohone

_"some rules are meant to be broken"_

**Comment by ZfsrGhS953** [comment]
This extension is really outdated. Use Cheat Engine instead. The client has no chance to detect it because it runs outside of the browser process.

**Comment by Windfall-Github** [comment]
I have tried to use cheat engine to give myself points, increase my score, and change zoom. I never go  it to work. I managed to change the number of upgrade points I had, but it wouldn't let me upgrade. Could you tell me how to  get it working?

thanks,
oneohone

**Comment by Excigma** [comment]
I assume upgrades and some other things are handled server side, and some things aren't possible to do

**Comment by Windfall-Github** [comment]
What are you doing here??? Bruhhhhhhh
