### ISSUE TITLE
Zoom out not working

### ISSUE THREAD

**Issue by Reeyaad** [terjanq/xDiep.io#2]
I'm so sorry to say that zoom out not working in this script.

**Comment by diepio** [comment]
Same here, couple hours ago was working fine, something changed today.

**Comment by Reeyaad** [comment]
Yeah.... it was working so fine..... without zoom out we can't get advantage while playing. zoom out is one of the most important features of this script.

**Comment by terjanq** [comment]
I've just added some buggy zoom

**Comment by diepio** [comment]
thanks for looking at this terjanq. Did try it, its a bit buggy but its a start I guess. When scrolling and leveling you cannot press + to increase attribute.

**Comment by Reeyaad** [comment]
Thank you Bro

**Comment by Reeyaad** [comment]
somthing is better than nothing lol :+1:

**Comment by Reeyaad** [comment]
@diepio yeah mate I agree with you... but you can easily solve it by pressing the keys from (1-8) to increase your desired stats and also you can press M+(Desired stat number) to maximize that stat... hope that it helps.

**Comment by terjanq** [comment]
Also if there is any bug you can just return to normal size :)

I'm not sure if I can get more than this, I was trying a little but without big progress.

**Comment by Reeyaad** [comment]
Thank you for trying :+1:
