### ISSUE TITLE
R.I.P

### ISSUE THREAD

**Issue by Reeyaad** [terjanq/xDiep.io#3]
your extention and script works but the screen turns black after sometime.... Thank you for making this, had alot of fun with it. THanks again,

**Comment by terjanq** [comment]
Should be fine now.. Can you try it?

It wasn't even intended to kill my extension, it was targeted to condoriano extension but accidentally my ext was down too

**Comment by Reeyaad** [comment]
Yeahhhhhhhhhhhhhhhh!! , it's working again!!!!!! THANK YOU :+1:
