### ISSUE TITLE
Dear Terjanq, please look at this. Thanks in advance.

### ISSUE THREAD

**Issue by Reeyaad** [terjanq/xDiep.io#9]
At first please pardon me because this is unrelated to your extention. Your extention is working just fine. I didn't have any way to contact you thats why I have given post here. 
Do you have any idea how they are controlling 3 tanks at the same time in the video??
It's pretty cool actually. Please let me know what you think about this......
Thanks  You.
Video link is given below.
https://www.youtube.com/watch?v=3IVaFA9de80

**Comment by hxxr** [comment]
I assume it could be something like [this?](http://lifehacker.com/254648/how-to-control-multiple-computers-with-a-single-keyboard-and-mouse) But of course, with one cursor on each monitor. But @terjanq might have a better answer. I am just listening to this project for some reason.

**Comment by Reeyaad** [comment]
Yeah maybe, thanks for your kind feedback... hxxr

**Comment by Reeyaad** [comment]
Very interesting :)

**Comment by terjanq** [comment]
I am sorry, its makeable of course but I'm done with diep.io as I told before.

**Comment by Reeyaad** [comment]
Okay never mind. I have found another way to do it, didn't test this yet https://youtu.be/C4oSi970S58
